sudo: required

#language: node_js

services:
  - docker

before_install:
  - docker build . -f Dockerfile.dev -t katchvidal/nextjs

script:
  - docker run -e CI=true -t katchvidal/nextjs

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockernext"
  env: "Dockernext-env"
  bucket_name: "elasticbeanstalk-us-east-2-970013430177"
  bucket_path: "dockernext"
  acces_key_id: $AWS_ACCES_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main
