#sudo: required

language: generic

services:
  - docker

#before_install:
#  - docker build . Dockerfile -t katchvidal/nextjs

#script:
#  - docker run -t katchvidal/nextjs

after_succes:
  - docker build . Dockerfile -t katchvidal/nextjs
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push katchvidal/nextjs

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockernext"
  env: "Dockernext-env"
  bucket_name: "elasticbeanstalk-us-east-2-970013430177"
  bucket_path: "dockernext"
  acces_key_id: $AWS_ACCES_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main
