FROM node:17

# enviroment PORT=3000
ENV PORT 3000 

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json /usr/src/app/
RUN npm install

# Copying source files
COPY . /usr/src/app

# Building app
RUN npm run build
EXPOSE 3000

# Running the app -> Ejecuta en entorno de Produccion
CMD "npm" "start"